### ISSUE TITLE
Security: Digit length on positive result confirmation.

### ISSUE THREAD

**Issue by darvell** [abopengov/contact-tracing-iOS#4]
https://github.com/abopengov/contact-tracing-iOS/blob/13aeebfc1b8fa02a938d0ee2ec31b19d837f970a/ABTraceTogether/Upload%20data/View%20Controllers/UploadDataStep2VC.swift#L21

Am I understanding this correctly, all that's required to mark a user/record as being positive is just a 6 digit pin?

**Comment by saraalmouaswas** [comment]
hi @darvell thanks for alerting us to this issue. The 6-alpha-numeric one-time-passcode is used as a security measure in the flow to upload user's encrypted contact tracing data and is not used to mark a user as testing positive for COVID-19. Thank you for your help on improving ABTraceTogether!
